const root=document.documentElement;
document.querySelector('#theme').addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('edgeflow-theme',root.dataset.theme)});
root.dataset.theme=localStorage.getItem('edgeflow-theme')||'dark';
const esc=(value)=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const pill=(value)=>{const key=(value||'').toLowerCase();const cls=key.includes('pass')?'pass':key.includes('fail')||key.includes('invalid')?'fail':'warn';return `<span class="pill ${cls}">${esc(value||'PENDING')}</span>`};
let allRuns=[];
function renderRuns(query=''){const body=document.querySelector('#rows');const rows=allRuns.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));body.innerHTML=rows.map(({manifest,validation})=>`<tr><td><code>${esc(manifest.run_id)}</code></td><td>${esc(manifest.plan_id)}</td><td>${esc(manifest.experiment_id)}</td><td>${esc(manifest.source_type)}</td><td>${pill(validation?.verdict||manifest.status)}</td><td>${validation?.policy_eligible?'eligible':'excluded'}</td></tr>`).join('');document.querySelector('table').hidden=!rows.length;document.querySelector('#empty').hidden=!!rows.length}
async function load(){try{const [health,inspect,runs,policies]=await Promise.all([fetch('/health').then(r=>r.json()),fetch('/api/v1/inspect',{method:'POST'}).then(r=>r.json()),fetch('/api/v1/runs').then(r=>r.json()),fetch('/api/v1/policies').then(r=>r.json())]);document.querySelector('#health').className='pill pass';document.querySelector('#health').textContent=`API ${health.status}`;document.querySelector('#gpu').textContent=inspect.gpu.name;document.querySelector('#fingerprint').textContent=inspect.fingerprint_id;allRuns=runs;document.querySelector('#runCount').textContent=runs.length;document.querySelector('#eligibleCount').textContent=runs.filter(x=>x.validation?.policy_eligible).length;document.querySelector('#policyCount').textContent=policies.length;renderRuns();const list=document.querySelector('#policyList');document.querySelector('#policyEmpty').hidden=!!policies.length;list.innerHTML=policies.map(p=>`<article class="policy"><div><b>${esc(p.policy_id)}</b><br><small>${esc(p.model_id)} · fallback ${esc(p.fallback_plan_id)}</small></div>${pill(p.status)}</article>`).join('')}catch(error){document.querySelector('#health').className='pill fail';document.querySelector('#health').textContent='API unavailable';console.error(error)}}
document.querySelector('#search').addEventListener('input',e=>renderRuns(e.target.value));load();
