from __future__ import annotations

import random
from typing import Any

from edgeflow.core.models import PromptBucket, PromptSource, SamplingSpec, WorkloadSpec
from edgeflow.core.serialization import sha256_value

CORPUS = (
    "Explain a careful systems design using concrete evidence and explicit assumptions. "
    "Compare latency throughput memory quality and startup cost under a reproducible workload. "
    "A trustworthy experiment records raw observations before producing any summary. "
    "Controlled interventions change one primary factor while holding the remaining variables fixed. "
    "Fallback paths protect correctness when a specialized optimization is outside its validated scope. "
    "Token distributions should represent realistic language rather than one repeated token. "
    "Confidence intervals and practical thresholds prevent noisy winners from becoming recommendations. "
    "Every public number must resolve to a run manifest validation verdict and raw artifact."
)


def parse_prompt_distribution(value: str) -> int | list[PromptBucket]:
    """Parse either `1024` or `512:0.25,1024:0.75`."""

    value = value.strip()
    if ":" not in value:
        return int(value)
    buckets: list[PromptBucket] = []
    for item in value.split(","):
        token_text, probability_text = item.split(":", 1)
        buckets.append(PromptBucket(tokens=int(token_text), probability=float(probability_text)))
    total = sum(bucket.probability for bucket in buckets)
    if abs(total - 1.0) > 1e-6:
        raise ValueError(f"prompt distribution probabilities sum to {total}, expected 1.0")
    return buckets


def create_workload(
    *,
    workload_id: str,
    model_id: str,
    prompt_distribution: str,
    output_tokens: int,
    concurrency: int = 1,
    batch_size: int = 1,
    session_requests: int = 20,
    quality_profile: str = "balanced",
    seed: int = 42,
    arrival_pattern: str = "closed_loop",
    request_rate: float | None = None,
) -> WorkloadSpec:
    prompt_tokens = parse_prompt_distribution(prompt_distribution)
    sample_identity = {
        "corpus": CORPUS,
        "seed": seed,
        "prompt_tokens": [item.model_dump() for item in prompt_tokens]
        if isinstance(prompt_tokens, list)
        else prompt_tokens,
    }
    return WorkloadSpec(
        workload_id=workload_id,
        model_id=model_id,
        prompt_source=PromptSource(
            type="synthetic",
            name="edgeflow-synthetic-v1",
            revision="1.0",
            sample_ids_sha256=sha256_value(sample_identity),
        ),
        prompt_tokens=prompt_tokens,
        output_tokens=output_tokens,
        batch_size=batch_size,
        concurrency=concurrency,
        arrival_pattern=arrival_pattern,  # type: ignore[arg-type]
        request_rate=request_rate,
        sampling=SamplingSpec(),
        seed=seed,
        streaming=True,
        session_requests=session_requests,
        quality_profile=quality_profile,  # type: ignore[arg-type]
        notes="Generated by EdgeFlow using exact target-tokenizer buckets.",
    )


def choose_prompt_tokens(workload: WorkloadSpec, iteration: int) -> int:
    if isinstance(workload.prompt_tokens, int):
        return workload.prompt_tokens
    generator = random.Random(workload.seed + iteration)
    draw = generator.random()
    cumulative = 0.0
    for bucket in workload.prompt_tokens:
        cumulative += bucket.probability
        if draw <= cumulative:
            return bucket.tokens
    return workload.prompt_tokens[-1].tokens


def build_exact_token_ids(tokenizer: Any, token_count: int, *, seed: int = 42) -> list[int]:
    """Create a deterministic, varied sequence with exactly `token_count` tokenizer IDs."""

    if token_count < 1:
        raise ValueError("token_count must be positive")
    encoded = tokenizer.encode(CORPUS, add_special_tokens=False)
    if len(set(encoded)) < 8:
        raise ValueError("Tokenizer produced insufficiently diverse synthetic source tokens")
    generator = random.Random(seed)
    offset = generator.randrange(len(encoded))
    rotated = encoded[offset:] + encoded[:offset]
    body: list[int] = []
    while len(body) < token_count:
        body.extend(rotated)
        generator.shuffle(rotated)
    body = body[:token_count]
    bos = getattr(tokenizer, "bos_token_id", None)
    if bos is not None and token_count > 1:
        body[0] = int(bos)
    if len(body) != token_count:
        raise AssertionError("exact token construction failed")
    return body
